######################################################################
# Automatically generated by qmake (2.01a) ven. nov. 20 20:56:36 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . HEADERS src
INCLUDEPATH += . HEADERS

# Input
HEADERS += HEADERS/Affichage.hpp HEADERS/MainMenu.hpp HEADERS/MainWindow.hpp
SOURCES += main.cpp src/main.cpp src/MainMenu.cpp src/MainWindow.cpp
