# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gabriel/university/l3/s5/in505/project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gabriel/university/l3/s5/in505/project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriel/university/l3/s5/in505/project/CMakeFiles /home/gabriel/university/l3/s5/in505/project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriel/university/l3/s5/in505/project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main2

# Build rule for target.
main2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main2
.PHONY : main2

# fast build rule for target.
main2/fast:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/build
.PHONY : main2/fast

#=============================================================================
# Target rules for targets named main2_autogen

# Build rule for target.
main2_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main2_autogen
.PHONY : main2_autogen

# fast build rule for target.
main2_autogen/fast:
	$(MAKE) -f CMakeFiles/main2_autogen.dir/build.make CMakeFiles/main2_autogen.dir/build
.PHONY : main2_autogen/fast

main2_autogen/mocs_compilation.o: main2_autogen/mocs_compilation.cpp.o

.PHONY : main2_autogen/mocs_compilation.o

# target to build an object file
main2_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/main2_autogen/mocs_compilation.cpp.o
.PHONY : main2_autogen/mocs_compilation.cpp.o

main2_autogen/mocs_compilation.i: main2_autogen/mocs_compilation.cpp.i

.PHONY : main2_autogen/mocs_compilation.i

# target to preprocess a source file
main2_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/main2_autogen/mocs_compilation.cpp.i
.PHONY : main2_autogen/mocs_compilation.cpp.i

main2_autogen/mocs_compilation.s: main2_autogen/mocs_compilation.cpp.s

.PHONY : main2_autogen/mocs_compilation.s

# target to generate assembly for a file
main2_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/main2_autogen/mocs_compilation.cpp.s
.PHONY : main2_autogen/mocs_compilation.cpp.s

src/bin/main2.o: src/bin/main2.cpp.o

.PHONY : src/bin/main2.o

# target to build an object file
src/bin/main2.cpp.o:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/src/bin/main2.cpp.o
.PHONY : src/bin/main2.cpp.o

src/bin/main2.i: src/bin/main2.cpp.i

.PHONY : src/bin/main2.i

# target to preprocess a source file
src/bin/main2.cpp.i:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/src/bin/main2.cpp.i
.PHONY : src/bin/main2.cpp.i

src/bin/main2.s: src/bin/main2.cpp.s

.PHONY : src/bin/main2.s

# target to generate assembly for a file
src/bin/main2.cpp.s:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/src/bin/main2.cpp.s
.PHONY : src/bin/main2.cpp.s

src/lib/AppWindow.o: src/lib/AppWindow.cpp.o

.PHONY : src/lib/AppWindow.o

# target to build an object file
src/lib/AppWindow.cpp.o:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/src/lib/AppWindow.cpp.o
.PHONY : src/lib/AppWindow.cpp.o

src/lib/AppWindow.i: src/lib/AppWindow.cpp.i

.PHONY : src/lib/AppWindow.i

# target to preprocess a source file
src/lib/AppWindow.cpp.i:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/src/lib/AppWindow.cpp.i
.PHONY : src/lib/AppWindow.cpp.i

src/lib/AppWindow.s: src/lib/AppWindow.cpp.s

.PHONY : src/lib/AppWindow.s

# target to generate assembly for a file
src/lib/AppWindow.cpp.s:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/src/lib/AppWindow.cpp.s
.PHONY : src/lib/AppWindow.cpp.s

src/lib/ArbreB.o: src/lib/ArbreB.cpp.o

.PHONY : src/lib/ArbreB.o

# target to build an object file
src/lib/ArbreB.cpp.o:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/src/lib/ArbreB.cpp.o
.PHONY : src/lib/ArbreB.cpp.o

src/lib/ArbreB.i: src/lib/ArbreB.cpp.i

.PHONY : src/lib/ArbreB.i

# target to preprocess a source file
src/lib/ArbreB.cpp.i:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/src/lib/ArbreB.cpp.i
.PHONY : src/lib/ArbreB.cpp.i

src/lib/ArbreB.s: src/lib/ArbreB.cpp.s

.PHONY : src/lib/ArbreB.s

# target to generate assembly for a file
src/lib/ArbreB.cpp.s:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/src/lib/ArbreB.cpp.s
.PHONY : src/lib/ArbreB.cpp.s

src/lib/Part2.o: src/lib/Part2.cpp.o

.PHONY : src/lib/Part2.o

# target to build an object file
src/lib/Part2.cpp.o:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/src/lib/Part2.cpp.o
.PHONY : src/lib/Part2.cpp.o

src/lib/Part2.i: src/lib/Part2.cpp.i

.PHONY : src/lib/Part2.i

# target to preprocess a source file
src/lib/Part2.cpp.i:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/src/lib/Part2.cpp.i
.PHONY : src/lib/Part2.cpp.i

src/lib/Part2.s: src/lib/Part2.cpp.s

.PHONY : src/lib/Part2.s

# target to generate assembly for a file
src/lib/Part2.cpp.s:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/src/lib/Part2.cpp.s
.PHONY : src/lib/Part2.cpp.s

src/lib/Sommet.o: src/lib/Sommet.cpp.o

.PHONY : src/lib/Sommet.o

# target to build an object file
src/lib/Sommet.cpp.o:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/src/lib/Sommet.cpp.o
.PHONY : src/lib/Sommet.cpp.o

src/lib/Sommet.i: src/lib/Sommet.cpp.i

.PHONY : src/lib/Sommet.i

# target to preprocess a source file
src/lib/Sommet.cpp.i:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/src/lib/Sommet.cpp.i
.PHONY : src/lib/Sommet.cpp.i

src/lib/Sommet.s: src/lib/Sommet.cpp.s

.PHONY : src/lib/Sommet.s

# target to generate assembly for a file
src/lib/Sommet.cpp.s:
	$(MAKE) -f CMakeFiles/main2.dir/build.make CMakeFiles/main2.dir/src/lib/Sommet.cpp.s
.PHONY : src/lib/Sommet.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... main2"
	@echo "... edit_cache"
	@echo "... main2_autogen"
	@echo "... main2_autogen/mocs_compilation.o"
	@echo "... main2_autogen/mocs_compilation.i"
	@echo "... main2_autogen/mocs_compilation.s"
	@echo "... src/bin/main2.o"
	@echo "... src/bin/main2.i"
	@echo "... src/bin/main2.s"
	@echo "... src/lib/AppWindow.o"
	@echo "... src/lib/AppWindow.i"
	@echo "... src/lib/AppWindow.s"
	@echo "... src/lib/ArbreB.o"
	@echo "... src/lib/ArbreB.i"
	@echo "... src/lib/ArbreB.s"
	@echo "... src/lib/Part2.o"
	@echo "... src/lib/Part2.i"
	@echo "... src/lib/Part2.s"
	@echo "... src/lib/Sommet.o"
	@echo "... src/lib/Sommet.i"
	@echo "... src/lib/Sommet.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

